#!/usr/bin/env node

/**
 * Module dependencies.
 */
const serverUtils = require('../utils/ServerUtils');
const app = require('../app');
const http = require('http');

/**
 * Get port from environment and store in Express.
 */

const port = serverUtils.normalizePort(process.env.PORT || '3000');
app.set('port', port);

/**
 * Create HTTP server.
 */

const server = http.createServer(app);

/**
 * Listen on provided port, on all network interfaces.
 */

server.listen(port);
server.on('error', (err) => { serverUtils.onError(err, port) });
server.on('listening', () => { serverUtils.onListening(server) });
